name: Lint Reference Files
on:
  push:
    paths: ['en-US/**.ftl' ]
    branches: [ main ]
  pull_request:
    paths: ['en-US/**.ftl' ]
    branches: [ main ]
  workflow_dispatch:
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install Python dependencies
        run: |
          pip install -r .github/requirements.txt
      - name: Lint reference
        run: |
          python .github/scripts/fluent_reference.py ./en-US
